ROWS = 15
COLS = 15
TILE_SIZE = 48
SIDE_PANEL = 300
SCREEN_WIDTH = TILE_SIZE * COLS
SCREEN_HEIGHT = TILE_SIZE * ROWS
FPS = 60
HEALTH = 100
MONEY = 2000
TOTAL_LEVELS = 15

#turret constants
TURRET_LEVELS = 5
BUY_COST = 200 #thật ra là biến thiên
INFLATION = 75 #thật ra là biến thiên
UPGRADE_COST = 20
LEVEL_COMPLETE_REWARD = 100
ANIMATION_STEPS = 8
ANIMATION_DELAY = 15
DAMAGE = 5